### ISSUE TITLE
Make usable on Ubuntu Core

### ISSUE THREAD

**Issue by dilyn-corner** [canonical/postgresql-snap#29]
On Ubuntu Core systems, there are no users to manage the system. In these cases, having the snap be configurable to create a cluster or, even better, exposing relevant postgresql bits to allow individual snaps to manage their own clusters, will make this snap more usable on Ubuntu Core.

For instance, this is some of the work I've done for my Ubuntu Core NAS - https://github.com/dilyn-corner/postgresql-snap

The minimum to resolve this issue would be to expose the postgresql files via  content interface:

```
# This slot exposes all of this snap to any other snap to use postgresql without
# bundling any of postgresql. This allows multiple snaps to use the postgresql
# snap however they see fit, without duplicating postgresql files on the device
# (by bundling postgresql with every snap)
slots:
  postgresql:
    interface: content
    content: bins
    read:
      - $SNAP
```

An added bonus would be making the postgresql daemon in this snap configurable (like what ubuntu-frame does https://github.com/canonical/ubuntu-frame/blob/5f4a14efd381855d68719264260fd55dcc3e003f/snap/hooks/configure#L103-L112).
